typedef enum {
  LCD_STATE_UNKNOWN,
  LCD_STATE_INCOMPLETE,
  LCD_STATE_POWERED_OFF,
  LCD_STATE_CODE_C,
  LCD_STATE_CODE_CO,
  LCD_STATE_CODE_COD,
  LCD_STATE_CODE_CODE,
  LCD_STATE_ERROR_NUM,
  LCD_STATE_ERROR_E,
  LCD_STATE_RUNNING
}LCD_STATE_T;
